version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: sftp_loader
      POSTGRES_USER: ${SFTP_DB_USER}
      POSTGRES_PASSWORD: ${SFTP_DB_PASS}
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile
    environment:
      SFTP_DB_USER: ${SFTP_DB_USER}
      SFTP_DB_PASS: ${SFTP_DB_PASS}
      SFTP_HOST: ${SFTP_HOST}
      SFTP_PORT: ${SFTP_PORT}
      SFTP_USER: ${SFTP_USER}
      SFTP_PASS: ${SFTP_PASS}
    depends_on:
      - db
    ports:
      - "8080:8080"
