spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sftp_loader
    username: ${SFTP_DB_USER}
    password: ${SFTP_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate

sftp:
  host: ${SFTP_HOST}
  port: ${SFTP_PORT:22}
  user: ${SFTP_USER}
  password: ${SFTP_PASS}
  remote-dir: /data

app:
  download-dir: D:/Downloads
  csv-file: D:/Downloads/download_history.csv
